### ISSUE TITLE
integrate sign-in feature for site with Microsoft logins

### ISSUE THREAD

**Issue by keyszl** [DiscoTrayStudios/Hendrix-SOS-Resources#3]

**Comment by mgoadric** [comment]
Yes! This will need to be through the Microsoft Entra and Graph API. This is the place to start

https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-web-app-dotnet-core-sign-in

I will need to do some admin work on the backend, let me know when you've started this issue.
